version: '3'

services:

  influxdb:
    image: "influxdb:latest"
    hostname: "influxdb"
    networks:
    - net_1 
    environment:
    - "INFLUXDB_DB=network_latency"

  telegraf:
    image: "telegraf:latest"
    hostname: "telegraf"
    networks:
    - net_1 
    volumes:
    - "./config/telegraf:/etc/telegraf:ro"
    - "./entrypoint_telegraf.sh:/entrypoint.sh:ro"

  grafana:
    image: "grafana/grafana:latest"
    hostname: "grafana"
    networks:
    - net_1
    ports:
    - "3000:3000"
    volumes:
    - "./config/grafana/provisioning:/etc/grafana/provisioning"
    environment:
    - "GF_SECURITY_ADMIN_PASSWORD=CHANGEME"
    - "GF_AUTH_ANONYMOUS_ENABLED=true"

networks:
  net_1:
