version: '3'

services:

  influxdb:
    image: "influxdb:1.8"
    restart: unless-stopped
    hostname: "influxdb"
    environment:
    - "INFLUXDB_DB=network_latency"
    networks:
    - net_latency
    volumes:
    - "influxdb:/var/lib/influxdb"

  telegraf:
    image: "telegraf:latest"
    restart: unless-stopped
    hostname: "telegraf"
    networks:
    - net_latency
    volumes:
    - "./config/telegraf:/etc/telegraf:ro"
    - "./config/entrypoint_telegraf.sh:/entrypoint.sh:ro"

  grafana:
    image: "grafana/grafana:latest"
    restart: unless-stopped
    hostname: "grafana"
    user: "root"
    environment:
    - "GF_SECURITY_ADMIN_PASSWORD=CHANGEME"
    - "GF_AUTH_ANONYMOUS_ENABLED=true"
    networks:
    - net_latency
    ports:
    - "3000:3000"
    volumes:
    - "./config/grafana/provisioning:/etc/grafana/provisioning"
    - "./config/grafana/plugins:/var/lib/grafana/plugins"
networks:
  net_latency:
volumes:
  influxdb:
